apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: zwhitchcox/hello-rust
        ports:
        - containerPort: 3030
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.1.86
  - 192.168.1.115
  - 192.168.1.118
  - 192.168.1.121
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3030
  selector:
    app: api
